FROM ubuntu:22.04 AS build

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    libpoco-dev \
    libpocodatapostgresql80 \
    libpq-dev \ 
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY . .
RUN cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-include /usr/include/postgresql/libpq-fe.h" && \
    cmake --build build -j$(nproc)


FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpoco-dev \
    libpocodatapostgresql80 \ 
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=build /src/build/API_Poco_PG /app/API_Poco_PG


EXPOSE 8080
CMD ["/app/API_Poco_PG"]